//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldsHardestGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldsHardestGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///	&lt;player&gt;
        ///		&lt;name&gt;dkgje&lt;/name&gt;
        ///		&lt;time&gt;325&lt;/time&gt;
        ///	&lt;/player&gt;
        ///	&lt;player&gt;
        ///		&lt;name&gt;wqwfw&lt;/name&gt;
        ///		&lt;time&gt;632&lt;/time&gt;
        ///	&lt;/player&gt;
        ///	&lt;player&gt;
        ///		&lt;name&gt;asfasdf&lt;/name&gt;
        ///		&lt;time&gt;123&lt;/time&gt;
        ///	&lt;/player&gt;
        ///	&lt;player&gt;
        ///		&lt;name&gt;wfewa&lt;/name&gt;
        ///		&lt;time&gt;456&lt;/time&gt;
        ///	&lt;/player&gt;
        ///	&lt;player&gt;
        ///		&lt;name&gt;ewafw&lt;/name&gt;
        ///		&lt;time&gt;789&lt;/time&gt;
        ///	&lt;/player&gt;
        ///	&lt;player&gt;
        ///		&lt;name&gt;ewafwe&lt;/name&gt;
        ///		&lt;time&gt;101&lt;/time&gt;
        ///	&lt;/player&gt;
        ///	&lt;player&gt;
        ///		&lt;name&gt;q234w&lt;/name&gt;
        ///		&lt;time&gt;122&lt;/time&gt;
        ///	&lt;/player&gt;
        ///	&lt;pla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HighscoreXml {
            get {
                return ResourceManager.GetString("HighscoreXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap luffy_face {
            get {
                object obj = ResourceManager.GetObject("luffy face", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pimpin_one_piece {
            get {
                object obj = ResourceManager.GetObject("pimpin one piece", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap poggers {
            get {
                object obj = ResourceManager.GetObject("poggers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
